### ISSUE TITLE
this.cliEngineCtor is not a constructor

### ISSUE THREAD

**Issue by passioncsu** [ATQQ/uni-vue3-ts-template#10]
如题怎么解决

**Comment by ATQQ** [comment]
怎么复现的呢？方便提供一下步骤和截图吗

**Comment by ATQQ** [comment]
我 Google了一下 这个应该是个eslint错误（不影响运行），在[webStorm ](https://github.com/eslint/eslint/issues/15677) 中
如果提示是编辑器告知的， 你看看是否正确安装了依赖
