### ISSUE TITLE
模板可以换成npm吗

### ISSUE THREAD

**Issue by sno163** [ATQQ/uni-vue3-ts-template#12]
大佬,请问模板能换成npm吗?

**Comment by ATQQ** [comment]
不限制包管理工具的使用，只是推荐pnpm  装包快一点

你用npm 可以直接 
```sh
npm install
```

**Comment by ATQQ** [comment]
这边使用**pnpm** 遇到什么问题了吗

**Comment by sno163** [comment]
> 这边使用**pnpm** 遇到什么问题了吗

好的,谢谢,去掉npx only-allow pnpm就可以了,没什么问题,只是好奇怎么用不了npm

**Comment by ATQQ** [comment]
没考虑周到，我下来把这个钩子删一下

**Comment by ATQQ** [comment]
最新模板已经移除
