### ISSUE TITLE
模板可以加入 tailwindcss 吗？

### ISSUE THREAD

**Issue by hxzAugustinus** [ATQQ/uni-vue3-ts-template#14]

**Comment by ATQQ** [comment]
可以直接来个PR

**Comment by ATQQ** [comment]
有朋友PR了 [unocss](https://github.com/unocss/unocss) ，在最新的模板。可以试试

![](https://fastly.jsdelivr.net/gh/MellowCo/image-host/2022/202211121156442.png)

PR https://github.com/ATQQ/uni-vue3-ts-template/pull/18

**Comment by ATQQ** [comment]
现有模板已有 [unocss](https://github.com/unocss/unocss) 原子化CSS方案。不计划再引入 tailwindcss
