### ISSUE TITLE
如何运行到真机

### ISSUE THREAD

**Issue by parz1** [ATQQ/uni-vue3-ts-template#19]
如图所示，直接引入项目安装完依赖运行后将会导致最新版HBuilderX-Alpha编译卡住
如果控制台运行pnpm dev:app 再导入HbuilderX则可以运行，而我需要引用原生插件，难以引入打基座。
环境是m1 mac os ventura 13.0.1
<img width="372" alt="Screenshot 2022-11-23 at 10 00 57" src="https://user-images.githubusercontent.com/32906370/203456130-4b47941a-5712-4c51-8289-d73ad587e7e4.png">

**Comment by ATQQ** [comment]
真机运行参考uni-app 官方的文档吧：https://uniapp.dcloud.net.cn/tutorial/run/run-app-faq.html

我理解不需要终端里运行 pnpm:dev:app 吧？直接用 HBuilderX-Alpha 编译就行了

M1编译报错，我README里留了解决办法，手动装一下 esbuild 非arm版本的依赖

这个是Hbuildex的bug 它不是 适配ARM的实现，只是用原来的intel 产物做了一个适配转换成的arm
