### ISSUE TITLE
编译到Web侧的支持

### ISSUE THREAD

**Issue by l290347877** [ATQQ/uni-vue3-ts-template#2]
运行后，vue版本是2.6.11 ，不是vue3 不知道问题出在哪了，求助

**Comment by ATQQ** [comment]
好滴，晚点儿我看下

**Comment by ATQQ** [comment]
你用指令看一下你项目的Vue版本呢?
```sh
yarn list vue
# 或者
npm list vue
```

![image](https://user-images.githubusercontent.com/42485491/142727950-eb16d200-c181-4e13-bd41-373934cdbaa6.png)

其次Vue3目前的tag还是latest，你安装的时候得加上 `next`这个 tag
```sh
yarn add vue@next
# 或者
npm i vue@next
```

![image](https://user-images.githubusercontent.com/42485491/142728033-4f40f691-bcc3-40de-bedf-0936c60e0f18.png)

**Comment by ATQQ** [comment]
模板我已经升级到 最新的vue3@next，还小优化了一下项目，你可以拉模板再跑一跑

**Comment by l290347877** [comment]
下拉之后运行小程序没有啥问题，之前运行错误是基于h5 的错误，发现已经去除了h5的支持。h5端是不可运行的吗

**Comment by ATQQ** [comment]
> 下拉之后运行小程序没有啥问题，之前运行错误是基于h5 的错误，发现已经去除了h5的支持。h5端是不可运行的吗

这个模板，是基于官方的做的一些定制，有些插件是只支持小程序侧的

如果确实希望一套同时跑小程序和Web，我下来看看，项目应该需要稍微改造一下

具体可以看：Dcloud的相关帖子 - https://ask.dcloud.net.cn/article/37834

**Comment by l290347877** [comment]
感谢up主分享

**Comment by l290347877** [comment]
建议更新一下ts的版本，在3.0.0 无法支持 vue3的 reactive, toRefs等组件

**Comment by ATQQ** [comment]
> 建议更新一下ts的版本，在3.0.0 无法支持 vue3的 reactive, toRefs等组件

收到 ，我下来 统一更新一波依赖

**Comment by ATQQ** [comment]
https://ask.dcloud.net.cn/m/article/37834

官方最新已经支持了，我下来迭代一下模板

**Comment by ATQQ** [comment]
已同步官方最新模板 - Vite + Vue3
