### ISSUE TITLE
新版本编译报错

### ISSUE THREAD

**Issue by yhf1414104530** [ATQQ/uni-vue3-ts-template#20]
.pnpm/vite@3.2.3_ppdxls77r7tfsxvxidunrbldv4/node_modules/vite/dist/node-cjs/publicUtils.cjs:64
11:10:41.068     const cache = options.cache ?? new SplitVendorChunkCache();
11:10:41.069                                  ^
11:10:41.072 SyntaxError: Unexpected token '?'
11:10:41.072     at wrapSafe (internal/modules/cjs/loader.js:915:16)
11:10:41.075     at Module._compile (internal/modules/cjs/loader.js:963:27)
11:10:41.078     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
11:10:41.082     at Module.load (internal/modules/cjs/loader.js:863:32)
11:10:41.082     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
11:10:41.085     at Module.require (internal/modules/cjs/loader.js:887:19)
11:10:41.088     at require (internal/modules/cjs/helpers.js:74:18)
11:10:41.091     at Object.<anonymous> (/Users/lvxiang/work_place/demo/test/uni-vue3-ts-template/node_modules/.pnpm/vite@3.2.3_ppdxls77r7tfsxvxidunrbldv4/node_modules/vite/index.cjs:7:31)
11:10:41.091     at Module._compile (internal/modules/cjs/loader.js:999:30)
11:10:41.095     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by ATQQ** [comment]
升级Hbuildex到最新的alpha版本了吗 https://www.dcloud.io/hbuilderx.html

![图片](https://img.cdn.sugarat.top/mdImg/MTY3MDIxMTM5NzgyMQ==670211397821)

**Comment by yhf1414104530** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/19488692/205545878-4c0653a5-ff2a-4eed-903f-5da11eedd84e.png">
![image](https://user-images.githubusercontent.com/19488692/205545937-1a266934-b623-4fd2-bebd-0e16e9f3019c.png)
你好 我升级了 还是一样

**Comment by yhf1414104530** [comment]
> 升级Hbuildex到最新的alpha版本了吗 https://www.dcloud.io/hbuilderx.html
> 
> ![图片](https://camo.githubusercontent.com/2bb28f38987c9995ac814069f168d4e61fc9021310227af4f369208760859a6b/68747470733a2f2f696d672e63646e2e737567617261742e746f702f6d64496d672f4d5459334d4449784d544d354e7a67794d513d3d363730323131333937383231)

谢谢 升级到alpha版本就可以啦
