### ISSUE TITLE
微信小程序，真机调试不显示内容

### ISSUE THREAD

**Issue by jiaqiyu543** [ATQQ/uni-vue3-ts-template#25]
微信小程序：开发模式模拟器显示正常，但是真机调试模式不显示内容，上传体验版也不行
![1](https://github.com/ATQQ/uni-vue3-ts-template/assets/29082639/3f0fa895-d134-4649-bf71-764d8f3c7be7)
![微信截图_20231115114833](https://github.com/ATQQ/uni-vue3-ts-template/assets/29082639/c1150a2f-6c30-416d-baf5-4e2fcb6f4d35)
![微信图片_20231115114919](https://github.com/ATQQ/uni-vue3-ts-template/assets/29082639/9e3c6379-d84e-4898-a46e-5493b407265f)

**Comment by ATQQ** [comment]
看看报错信息 什么呢？这个白屏肯定有报错 信息，对着报错才能看什么问题

**Comment by jiaqiyu543** [comment]
![微信截图_20231116093533](https://github.com/ATQQ/uni-vue3-ts-template/assets/29082639/afc58655-6fc5-4497-9993-1b2fd5fbb4a1)
没有任何报错， 已经找到原因了 我使用DEV模式运行微信小程序，真机调试的时候因为加载的内容太大导致不显示（猜测的），用build模式真机调试就可以了  建议在readme 说明一下  抱歉 一个菜鸟

**Comment by ATQQ** [comment]
OK  我记一下这个，本周 找时间优化一下文档

---
还有你那边是拉的Github的模板还是，Dcloud上下载的

**Comment by jiaqiyu543** [comment]
直接从github下载的

**Comment by ATQQ** [comment]
更新到 README 了 这个FAQ @jiaqiyu543 

感谢反馈
