### ISSUE TITLE
是否方便维护一个非TS分支？

### ISSUE THREAD

**Issue by zaxlct** [ATQQ/uni-vue3-ts-template#6]
感谢开源，谢谢
或者如果不想用 TS，除了把 .ts 语法改为 js 外，还需要哪些改动？我来改改然后提交个 PR 也可以

**Comment by ATQQ** [comment]
我理解是兼容的。你可以扒拉下来直接把ts后缀改成js

**Comment by ATQQ** [comment]
我先记一下，回头抽个时间 CV 一份JS的

**Comment by ATQQ** [comment]
@zaxlct 见这个仓库 https://github.com/ATQQ/uni-app-template

纯JS的模板，和这个TS模板的特性一样

**Comment by ATQQ** [comment]
见这个仓库 https://github.com/ATQQ/uni-app-template
